# Generated by Django 3.2 on 2021-05-19 15:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя Категрии')),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название поста')),
                ('slug', models.SlugField(unique=True)),
                ('content', models.TextField()),
                ('description', models.CharField(max_length=50, verbose_name='Описание Поста')),
                ('image', models.ImageField(upload_to='')),
                ('in_archive', models.BooleanField(default=False)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('blog_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.blogcategory', verbose_name='Категория')),
                ('related_posts', models.ManyToManyField(blank=True, null=True, to='main.BlogPost')),
            ],
        ),
        migrations.CreateModel(
            name='ImageForPosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('blog_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.blogpost', verbose_name='Пост для которого будут бодалены фото')),
            ],
        ),
    ]
